### ISSUE TITLE
Running locally does not work

### ISSUE THREAD

**Issue by xzores** [TinyTapeout/vga-playground#14]
I have installed the newest version of npm and ran the 2 commands as instructed, but i get the error:

```
root@LAPTOP-DKKBVOIS:~/my_designs/vga-playground# npm start

> vga-playground@1.0.0 start
> vite

file:///root/my_designs/vga-playground/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by urish** [comment]
Looks like your node.js version is too old - please try with a recent version (20.x)

**Comment by xzores** [comment]
Solved it!
